Repository SotMSteamMods/CauldronMods, pull requests merged in 2020-11, with the labels that each got.

#136 Typo fix in bug report template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: bug

#131 Fix of 77 in play issue
  Controller/Heroes/Necro/CardSubClasses/UndeadCardController.cs
  Controller/Heroes/Necro/Cards/AbominationCardController.cs
  Controller/Heroes/Necro/Cards/DemonicImpCardController.cs
  Controller/Heroes/Necro/Cards/GhoulCardController.cs
  Controller/Heroes/Necro/Cards/NecroZombieCardController.cs
  Controller/Heroes/Necro/Cards/PossessedCorpseCardController.cs
Labels: bug

#128 Issue #127
  Controller/Environments/TheWanderingIsle/Cards/AncientParasiteCardController.cs
  Testing/Environments/TheWanderingIsleTests.cs
Labels: bug

#139 Update HealingMagicCardController.cs
  Controller/Villains/Tiamat/Cards/HealingMagicCardController.cs
Labels: bug

#137 Bugfixes Baccarat and FSC
  Controller/Heroes/Baccarat/CardSubClasses/AceOfCardController.cs
  Controller/Heroes/Baccarat/Cards/AceOfSaintsCardController.cs
  Controller/Heroes/Baccarat/Cards/AceOfSinnersCardController.cs
  Controller/Heroes/Baccarat/Cards/BringDownTheHouseCardController.cs
  Controller/Heroes/Baccarat/Cards/GraveyardBridgeCardController.cs
  Controller/Heroes/Baccarat/CharacterCards/BaccaratCharacterCardController.cs
  DeckLists/Environment/FSCContinuanceWandererDeckList.json
  Testing/Heroes/BaccaratTests.cs
Labels: bug, enhancement

#142 121, 135 issue fixes
  Controller/Heroes/TheStranger/CardSubClasses/RuneCardController.cs
  Controller/Heroes/TheStranger/Cards/UnweaveCardController.cs
  Testing/Heroes/TheStrangerTests.cs
Labels: bug

#143 Fixed issue 68
  Controller/Heroes/TheStranger/CardSubClasses/GlyphCardController.cs
Labels: bug

#146 Issue 80 before timing prevention fixes
  Controller/Heroes/DocHavoc/Cards/CauterizeCardController.cs
  Controller/Heroes/TangoOne/Cards/ChameleonArmorCardController.cs
  Controller/Heroes/TangoOne/Cards/CriticalHitCardController.cs
Labels: bug

#145 Fixed issue #144
  Controller/Heroes/Necro/Cards/TalismanCardController.cs
  Testing/Heroes/NecroTests.cs
Labels: bug

#56 Starlight Peer Review
  Controller/Heroes/Starlight/CardSubClasses/AncientConstellationGenericCardController.cs
  Controller/Heroes/Starlight/CardSubClasses/StarlightCardController.cs
  Controller/Heroes/Starlight/Cards/AncientConstellationACardController.cs
  Controller/Heroes/Starlight/Cards/AncientConstellationBCardController.cs
  Controller/Heroes/Starlight/Cards/AncientConstellationCCardController.cs
  Controller/Heroes/Starlight/Cards/AncientConstellationDCardController.cs
  Controller/Heroes/Starlight/Cards/AncientConstellationECardController.cs
  Controller/Heroes/Starlight/Cards/AncientConstellationFCardController.cs
  Controller/Heroes/Starlight/Cards/CelestialAuraCardController.cs
  Controller/Heroes/Starlight/Cards/EventHorizonCardController.cs
  Controller/Heroes/Starlight/Cards/ExodusCardController.cs
  Controller/Heroes/Starlight/Cards/GoldenAstrolabeCardController.cs
  Controller/Heroes/Starlight/Cards/NightloreArmorCardController.cs
  Controller/Heroes/Starlight/Cards/NovaShieldCardController.cs
  Controller/Heroes/Starlight/Cards/PillarsOfCreationCardController.cs
  Controller/Heroes/Starlight/Cards/RedshiftCardController.cs
  Controller/Heroes/Starlight/Cards/RetreatIntoTheNebulaCardController.cs
  Controller/Heroes/Starlight/Cards/StellarWindCardController.cs
  Controller/Heroes/Starlight/Cards/WarpHaloCardController.cs
  Controller/Heroes/Starlight/Cards/WishCardController.cs
  Controller/Heroes/Starlight/CharacterCards/StarlightCharacterCardController.cs
  DeckLists/Hero/StarlightDeckList.json
  Docs/manifest.json
  Testing/Heroes/StarlightTests.cs
Labels: Deck Peer Review Pending

#165 Bug fixes
  Controller/Heroes/DocHavoc/Cards/CauterizeCardController.cs
  Controller/Heroes/TangoOne/Cards/ChameleonArmorCardController.cs
  Controller/Heroes/TangoOne/Cards/CriticalHitCardController.cs
Labels: confirmed bug

#155 Doc havoc Issue Fixes #90 & #86
  Controller/Heroes/DocHavoc/Cards/BrawlerCardController.cs
  Controller/Heroes/DocHavoc/Cards/CauterizeCardController.cs
  Controller/Heroes/DocHavoc/Cards/DocsFlaskCardController.cs
  Controller/Heroes/DocHavoc/Cards/FieldDressingCardController.cs
  Controller/Heroes/DocHavoc/Cards/GasMaskCardController.cs
  Controller/Heroes/DocHavoc/Cards/ImmediateEvacCardController.cs
  Controller/Heroes/DocHavoc/Cards/ImprovisedMineCardController.cs
  Controller/Heroes/DocHavoc/Cards/PainkillersCardController.cs
  Controller/Heroes/DocHavoc/Cards/PhosphorBlastCardController.cs
  Controller/Heroes/DocHavoc/Cards/RapidRegenCardController.cs
  Controller/Heroes/DocHavoc/Cards/RecklessChargeCardController.cs
  Controller/Heroes/DocHavoc/Cards/SearchAndRescueCardController.cs
  Controller/Heroes/DocHavoc/Cards/StimShotCardController.cs
  Controller/Heroes/DocHavoc/Cards/SyringeDartsCardController.cs
  Controller/Heroes/DocHavoc/Cards/UnstableSerumCardController.cs
  Controller/Heroes/DocHavoc/CharacterCards/DocHavocCharacterCardController.cs
  DeckLists/Hero/DocHavocDeckList.json
  Testing/Heroes/DocHavocTests.cs
Labels: confirmed bug

#164 Stranger fixes
  Controller/Heroes/TheStranger/CardSubClasses/GlyphCardController.cs
  Controller/Heroes/TheStranger/CardSubClasses/RuneCardController.cs
  Controller/Heroes/TheStranger/Cards/FlickeringWebCardController.cs
  Controller/Heroes/TheStranger/Cards/GlyphOfDecayCardController.cs
  Controller/Heroes/TheStranger/Cards/MarkOfDestructionCardController.cs
  Testing/Heroes/TheStrangerTests.cs
Labels: confirmed bug

#154 Blackwood forest
  Controller/Environments/BlackwoodForest/Cards/DenseBramblesCardController.cs
  Controller/Environments/BlackwoodForest/Cards/DesolationCardController.cs
  Controller/Environments/BlackwoodForest/Cards/DontStrayFromThePathCardController.cs
  Controller/Environments/BlackwoodForest/Cards/MirrorWraithCardController.cs
  Controller/Environments/BlackwoodForest/Cards/OldBonesCardController.cs
  Controller/Environments/BlackwoodForest/Cards/OvergrownCathedralCardController.cs
  Controller/Environments/BlackwoodForest/Cards/ShadowStalkerCardController.cs
  Controller/Environments/BlackwoodForest/Cards/ShadowWeaverCardController.cs
  Controller/Environments/BlackwoodForest/Cards/TheBlackTreeCardController.cs
  Controller/Environments/BlackwoodForest/Cards/TheHoundCardController.cs
  Controller/Environments/BlackwoodForest/Cards/VengefulSpiritsCardController.cs
  Controller/Environments/BlackwoodForest/Cards/WillOTheWispCardController.cs
  DeckLists/Environment/BlackwoodForestDeckList.json
  DeckLists/Environment/BlackwoodForestDecklist.json
  Testing/Environments/BlackwoodForestTests.cs
Labels: Deck Peer Review Pending

#186 Baccarat bugfixes
  Controller/Heroes/Baccarat/Cards/BringDownTheHouseCardController.cs
  Controller/Heroes/Baccarat/Cards/GraveyardBridgeCardController.cs
  Testing/Heroes/BaccaratTests.cs
Labels: confirmed bug

#48 Gray Peer Review
  Controller/Villains/Gray/CardSubClasses/GrayCardController.cs
  Controller/Villains/Gray/Cards/AlistarWintersCardController.cs
  Controller/Villains/Gray/Cards/BlightTheLandCardController.cs
  Controller/Villains/Gray/Cards/ChainReactionCardController.cs
  Controller/Villains/Gray/Cards/ContaminationCardController.cs
  Controller/Villains/Gray/Cards/CriticalMassCardController.cs
  Controller/Villains/Gray/Cards/HeavyRadiationCardController.cs
  Controller/Villains/Gray/Cards/IrradiatedTouchCardController.cs
  Controller/Villains/Gray/Cards/LivingReactorCardController.cs
  Controller/Villains/Gray/Cards/MutatedWildlifeCardController.cs
  Controller/Villains/Gray/Cards/NuclearFireCardController.cs
  Controller/Villains/Gray/Cards/RadioactiveCascadeCardController.cs
  Controller/Villains/Gray/Cards/UnstableIsotopeCardController.cs
  Controller/Villains/Gray/Cards/UnwittingHenchmenCardController.cs
  Controller/Villains/Gray/CharacterCards/GrayCharacterCardController.cs
  Controller/Villains/Gray/CharacterCards/GrayTurnTakerController.cs
  DeckLists/Villain/GrayDeckList.json
  Testing/Villains/GrayTests.cs
  Utility/CodingBugs
Labels: Deck Peer Review Pending

#51 St simeons catacombs
  Controller/Environments/StSimeonsCatacombs/Cards/AqueductsCardController.cs
  Controller/Environments/StSimeonsCatacombs/Cards/BreathStealerCardController.cs
  Controller/Environments/StSimeonsCatacombs/Cards/CoalKidCardController.cs
  Controller/Environments/StSimeonsCatacombs/Cards/CursedVaultCardController.cs
  Controller/Environments/StSimeonsCatacombs/Cards/DarkPassengerCardController.cs
  Controller/Environments/StSimeonsCatacombs/Cards/GhostCardController.cs
  Controller/Environments/StSimeonsCatacombs/Cards/LabyrinthGuideCardController.cs
  Controller/Environments/StSimeonsCatacombs/Cards/LivingGeometryCardController.cs
  Controller/Environments/StSimeonsCatacombs/Cards/PanicCardController.cs
  Controller/Environments/StSimeonsCatacombs/Cards/PoltergeistCardController.cs
  Controller/Environments/StSimeonsCatacombs/Cards/PossessorCardController.cs
  Controller/Environments/StSimeonsCatacombs/Cards/SacrificialShrineCardController.cs
  Controller/Environments/StSimeonsCatacombs/Cards/ScurryingEvilCardController.cs
  Controller/Environments/StSimeonsCatacombs/Cards/StSimeonsCatacombsCardController.cs
  Controller/Environments/StSimeonsCatacombs/Cards/StSimeonsCatacombsInstructionsCardController.cs
  Controller/Environments/StSimeonsCatacombs/Cards/TerriblePresenceCardController.cs
  Controller/Environments/StSimeonsCatacombs/Cards/TortureChamberCardController.cs
  Controller/Environments/StSimeonsCatacombs/Cards/TwistingPassagesCardController.cs
  Controller/Environments/StSimeonsCatacombs/TurnTaker/StSimeonsCatacombsTurnTakerController.cs
  Controller/Heroes/DocHavoc/Cards/BrawlerCardController.cs
  DeckLists/Environment/StSimeonsCatacombsDeckList.json
  Testing/BaseTest.cs
  Testing/Environments/StSimeonsCatacombsTests.cs
Labels: Deck Peer Review Pending

#133 Quicksilver
  Controller/Heroes/Quicksilver/CardSubClasses/ComboCardController.cs
  Controller/Heroes/Quicksilver/Cards/AlloyStormCardController.cs
  Controller/Heroes/Quicksilver/Cards/CoalescingSpearCardController.cs
  Controller/Heroes/Quicksilver/Cards/ComboChainCardController.cs
  Controller/Heroes/Quicksilver/Cards/ForestOfNeedlesCardController.cs
  Controller/Heroes/Quicksilver/Cards/FrenziedMeleeCardController.cs
  Controller/Heroes/Quicksilver/Cards/GuardBreakerCardController.cs
  Controller/Heroes/Quicksilver/Cards/IronRetortCardController.cs
  Controller/Heroes/Quicksilver/Cards/LiquidMetalCardController.cs
  Controller/Heroes/Quicksilver/Cards/MalleableArmorCardController.cs
  Controller/Heroes/Quicksilver/Cards/MercuryStrikeCardController.cs
  Controller/Heroes/Quicksilver/Cards/MirrorShardCardController.cs
  Controller/Heroes/Quicksilver/Cards/StressHardeningCardController.cs
  Controller/Heroes/Quicksilver/Cards/TestSubjectHalberdCardController.cs
  Controller/Heroes/Quicksilver/Cards/ViciousMemoriesCardController.cs
  Controller/Heroes/Quicksilver/Cards/WhisperingSteelCardController.cs
  Controller/Heroes/Quicksilver/CharacterCards/QuicksilverCharacterCardController.cs
  DeckLists/Hero/QuicksilverDeckList.json
  Testing/Heroes/QuicksilverTests.cs
Labels: Deck Peer Review Pending, help wanted

#193 Dendron
  Controller/Villains/Dendron/CardSubClasses/DendronBaseCardController.cs
  Controller/Villains/Dendron/CardSubClasses/DendronBaseCharacterCardController.cs
  Controller/Villains/Dendron/Cards/AdornedOakCardController.cs
  Controller/Villains/Dendron/Cards/BloodThornAuraCardController.cs
  Controller/Villains/Dendron/Cards/ChokingInscriptionCardController.cs
  Controller/Villains/Dendron/Cards/DarkDesignCardController.cs
  Controller/Villains/Dendron/Cards/InkScarCardController.cs
  Controller/Villains/Dendron/Cards/LivingInkCardController.cs
  Controller/Villains/Dendron/Cards/MarkOfTheWrithingNightCardController.cs
  Controller/Villains/Dendron/Cards/ObsidianSkinCardController.cs
  Controller/Villains/Dendron/Cards/PaintedViperCardController.cs
  Controller/Villains/Dendron/Cards/RestorationCardController.cs
  Controller/Villains/Dendron/Cards/ShadedOwlCardController.cs
  Controller/Villains/Dendron/Cards/StainedWolfCardController.cs
  Controller/Villains/Dendron/Cards/TintedStagCardController.cs
  Controller/Villains/Dendron/Cards/UrsaMajorCardController.cs
  Controller/Villains/Dendron/CharacterCards/DendronCharacterCardController.cs
  Controller/Villains/Dendron/CharacterCards/DendronTurnTakerController.cs
  Docs/manifest.json
  Testing/Villains/DendronTests.cs
Labels: Deck Peer Review Pending

#228 Bugfixes gray baccarat
  Controller/Heroes/Baccarat/Cards/AfterlifeEuchreCardController.cs
  DeckLists/Hero/CricketDeckList.json
  DeckLists/Villain/GrayDeckList.json
  Testing/Heroes/BaccaratTests.cs
Labels: confirmed bug

#245 Colors of backgrounds and health
  DeckLists/Environment/BlackwoodForestDeckList.json
  DeckLists/Environment/CatchwaterHarborDeckList.json
  DeckLists/Environment/FSCContinuanceWandererDeckList.json
  DeckLists/Environment/HalberdExperimentalResearchCenterDeckList.json
  DeckLists/Environment/NightloreCitadelDeckList.json
  DeckLists/Environment/NorthsparDeckList.json
  DeckLists/Environment/StSimeonsCatacombsDeckList.json
  DeckLists/Environment/SuperstormAkelaDeckList.json
  DeckLists/Environment/TheChasmOfAThousandNightsDeckList.json
  DeckLists/Environment/TheCybersphereDeckList.json
  DeckLists/Environment/TheWanderingIsleDeckList.json
  DeckLists/Environment/VaultFiveDeckList.json
  DeckLists/Environment/WindmillCityDeckList.json
  DeckLists/Hero/BaccaratDeckList.json
  DeckLists/Hero/CricketDeckList.json
  DeckLists/Hero/CypherDeckList.json
  DeckLists/Hero/DocHavocDeckList.json
  DeckLists/Hero/DriftDeckList.json
  DeckLists/Hero/EchelonDeckList.json
  DeckLists/Hero/GargoyleDeckList.json
  DeckLists/Hero/GyrosaurDeckList.json
  DeckLists/Hero/ImpactDeckList.json
  DeckLists/Hero/LadyOfTheWoodDeckList.json
  DeckLists/Hero/MagnificentMaraDeckList.json
  DeckLists/Hero/MalichaeDeckList.json
  DeckLists/Hero/NecroDeckList.json
  DeckLists/Hero/PyreDeckList.json
  DeckLists/Hero/QuicksilverDeckList.json
  DeckLists/Hero/StarlightDeckList.json
  DeckLists/Hero/TangoOneDeckList.json
  DeckLists/Hero/TerminusDeckList.json
  DeckLists/Hero/TheKnightDeckList.json
  DeckLists/Hero/TheStrangerDeckList.json
  DeckLists/Hero/TitanDeckList.json
  DeckLists/Hero/VanishDeckList.json
  DeckLists/Villain/AnathemaDeckList.json
  DeckLists/Villain/CalderochDeckList.json
  DeckLists/Villain/DendronDeckList.json
  DeckLists/Villain/DynamoDeckList.json
  DeckLists/Villain/GrayDeckList.json
  DeckLists/Villain/MenagerieDeckList.json
  DeckLists/Villain/MythosDeckList.json
  DeckLists/Villain/OriphelDeckList.json
  DeckLists/Villain/OutlanderDeckList.json
  DeckLists/Villain/PhaseDeckList.json
  DeckLists/Villain/ScreaMachineDeckList.json
  DeckLists/Villain/SwarmEaterDeckList.json
  DeckLists/Villain/TheInfernalChoirDeckList.json
  DeckLists/Villain/TheMistressOfFateDeckList.json
  DeckLists/Villain/TheRamDeckList.json
  DeckLists/Villain/TiamatDeckList.json
  DeckLists/Villain/VectorDeckList.json
Labels: enhancement

#247 Northspar
  Controller/Environments/Northspar/CardSubClasses/NorthsparCardController.cs
  Controller/Environments/Northspar/CardSubClasses/ThirdWaypointCardController.cs
  Controller/Environments/Northspar/Cards/AethiumVeinCardController.cs
  Controller/Environments/Northspar/Cards/AlienFungusCardController.cs
  Controller/Environments/Northspar/Cards/BitterColdCardController.cs
  Controller/Environments/Northspar/Cards/DemolishedCampCardController.cs
  Controller/Environments/Northspar/Cards/EerieStillnessCardController.cs
  Controller/Environments/Northspar/Cards/FrostbiteCardController.cs
  Controller/Environments/Northspar/Cards/FrozenSolidCardController.cs
  Controller/Environments/Northspar/Cards/LandingSiteCardController.cs
  Controller/Environments/Northspar/Cards/LostInTheSnowCardController.cs
  Controller/Environments/Northspar/Cards/MakeshiftShelterCardController.cs
  Controller/Environments/Northspar/Cards/RagingBlizzardCardController.cs
  Controller/Environments/Northspar/Cards/SnowShriekerCardController.cs
  Controller/Environments/Northspar/Cards/SupplyDepotCardController.cs
  Controller/Environments/Northspar/Cards/TakAhabCardController.cs
  Controller/Environments/Northspar/Cards/WhatsLeftOfThemCardController.cs
  Docs/manifest.json
  Testing/Environments/NorthsparTests.cs
Labels: Deck Peer Review Pending

#252 Quicksilver bugfixes
  Controller/Heroes/Quicksilver/Cards/LiquidMetalCardController.cs
  Controller/Heroes/Quicksilver/Cards/MalleableArmorCardController.cs
Labels: confirmed bug, enhancement

#249 The Ram
  Controller/Villains/TheRam/CardSubClasses/TheRamUtilityCardController.cs
  Controller/Villains/TheRam/CardSubClasses/TheRamUtilityCharacterCardController.cs
  Controller/Villains/TheRam/Cards/BarrierBusterCardController.cs
  Controller/Villains/TheRam/Cards/FallBackCardController.cs
  Controller/Villains/TheRam/Cards/FallingMeteorCardController.cs
  Controller/Villains/TheRam/Cards/ForcefieldNodeCardController.cs
  Controller/Villains/TheRam/Cards/GrapplingClawCardController.cs
  Controller/Villains/TheRam/Cards/PersonalDefenseSpinesCardController.cs
  Controller/Villains/TheRam/Cards/PowerNodeCardController.cs
  Controller/Villains/TheRam/Cards/RechargeCircuitsCardController.cs
  Controller/Villains/TheRam/Cards/RemoteMortarCardController.cs
  Controller/Villains/TheRam/Cards/RocketPodCardController.cs
  Controller/Villains/TheRam/Cards/UpCloseCardController.cs
  Controller/Villains/TheRam/CharacterCards/TheRamCharacterCardController.cs
  Controller/Villains/TheRam/CharacterCards/TheRamTurnTakerController.cs
  DeckLists/Villain/TheRamDeckList.json
  Docs/manifest.json
  Testing/Villains/TheRamTests.cs
Labels: Deck Peer Review Pending

#39 FSC Continuance Wanderer Peer Review
  Controller/Environments/FSCContinuanceWanderer/Cards/CombatCyborgCardController.cs
  Controller/Environments/FSCContinuanceWanderer/Cards/HeartOfTheWandererCardController.cs
  Controller/Environments/FSCContinuanceWanderer/Cards/ParadoxIntrusionCardController.cs
  Controller/Environments/FSCContinuanceWanderer/Cards/PrehistoricBehemothCardController.cs
  Controller/Environments/FSCContinuanceWanderer/Cards/SuperimposedRealitiesCardController.cs
  Controller/Environments/FSCContinuanceWanderer/Cards/TemporalAccelerationCardController.cs
  Controller/Environments/FSCContinuanceWanderer/Cards/TemporalResetCardController.cs
  Controller/Environments/FSCContinuanceWanderer/Cards/TemporalReversalCardController.cs
  Controller/Environments/FSCContinuanceWanderer/Cards/TemporalSlipstreamCardController.cs
  Controller/Environments/FSCContinuanceWanderer/Cards/TimeFreezeCardController.cs
  Controller/Environments/FSCContinuanceWanderer/Cards/VortexGlitchCardController.cs
  Controller/Environments/FSCContinuanceWanderer/Cards/VortexInterferenceCardController.cs
  Controller/Environments/FSCContinuanceWanderer/Cards/VortexSurgeCardController.cs
  DeckLists/Environment/FSCContinuanceWandererDeckList.json
  Testing/Environments/FSCContinuanceWandererTests.cs
Labels: Deck Peer Review Pending

#172 Vanish deck and controllers
  Controller/Heroes/Vanish/Cards/AbductAndAbandonController.cs
  Controller/Heroes/Vanish/Cards/BlindsideJumpCardController.cs
  Controller/Heroes/Vanish/Cards/BlinkCardController.cs
  Controller/Heroes/Vanish/Cards/ConcussiveBurstCardController.cs
  Controller/Heroes/Vanish/Cards/ElusiveCardController.cs
  Controller/Heroes/Vanish/Cards/FlashReconCardController.cs
  Controller/Heroes/Vanish/Cards/FlickeringStrikeCardController.cs
  Controller/Heroes/Vanish/Cards/FocusingGauntletCardController.cs
  Controller/Heroes/Vanish/Cards/ForewarnedCardController.cs
  Controller/Heroes/Vanish/Cards/JauntingReflexController.cs
  Controller/Heroes/Vanish/Cards/TacticalRelocationCardController.cs
  Controller/Heroes/Vanish/Cards/TeleportBarrageCardController.cs
  Controller/Heroes/Vanish/Cards/TranslocationAcceleratorController.cs
  Controller/Heroes/Vanish/CharacterCards/VanishCharacterCardController.cs
  DeckLists/Hero/VanishDeckList.json
  Docs/manifest.json
  Testing/Heroes/VanishTests.cs
Labels: Deck Peer Review Pending

#256 Tango one promos
  Controller/Heroes/TangoOne/CharacterCards/GhostOpsTangoOneCharacterCardController.cs
  Controller/Heroes/TangoOne/CharacterCards/PastTangoOneCharacterCardController.cs
  Testing/Heroes/TangoOnePromoTests.cs
Labels: enhancement

#268 The Stranger - Special Strings
  Controller/Heroes/TheStranger/Cards/FlickeringWebCardController.cs
  Controller/Heroes/TheStranger/Cards/MarkOfDestructionCardController.cs
  Controller/Heroes/TheStranger/Cards/TheOldRoadsCardController.cs
  Controller/Heroes/TheStranger/Cards/UnweaveCardController.cs
  Controller/Heroes/TheStranger/Cards/WhisperedSignsCardController.cs
Labels: enhancement

#267 Several - fix for issue #159 - Cards not added to IncreasePhaseActionCount list
  Controller/Heroes/DocHavoc/Cards/RecklessChargeCardController.cs
  Controller/Heroes/Malichae/Cards/UnshackledCardController.cs
  Controller/Heroes/TheStranger/Cards/MarkOfQuickeningCardController.cs
Labels: confirmed bug

#283 First Response Doc Havoc promo
  Controller/Heroes/DocHavoc/CharacterCards/FirstResponseDocHavocCharacterCardController.cs
  DeckLists/Hero/DocHavocDeckList.json
  Testing/Heroes/DocHavocPromoTests.cs
Labels: enhancement

#288 Removed logic for adding back in the don't play cards logic when flip…
  Controller/Environments/StSimeonsCatacombs/Cards/StSimeonsCatacombsInstructionsCardController.cs
  Testing/Environments/StSimeonsCatacombsTests.cs
Labels: confirmed bug

#289 WanderingIsle - fix for #278
  Controller/Environments/TheWanderingIsle/Cards/AncientParasiteCardController.cs
Labels: confirmed bug

#292 Wandering Isle - More Islandquake fixes
  Controller/Environments/TheWanderingIsle/Cards/IslandquakeCardController.cs
  Testing/Environments/TheWanderingIsleTests.cs
Labels: confirmed bug

#294 Maze of mirrors compliance
  Controller/Environments/FSCContinuanceWanderer/Cards/ParadoxIntrusionCardController.cs
  Controller/Environments/HalberdExperimentalResearchCenter/Cards/HalberdAlphaCardController.cs
  Controller/Environments/HalberdExperimentalResearchCenter/Cards/HalberdEtherCardController.cs
  Controller/Environments/HalberdExperimentalResearchCenter/Cards/HalberdFoamcoreCardController.cs
  Controller/Environments/HalberdExperimentalResearchCenter/Cards/HalberdOmegaCardController.cs
  Controller/Environments/HalberdExperimentalResearchCenter/Cards/HalberdPlasmaCardController.cs
  Controller/Environments/HalberdExperimentalResearchCenter/Cards/HalberdSirenCardController.cs
  Controller/Environments/HalberdExperimentalResearchCenter/Cards/HalberdSplinterCardController.cs
  Controller/Environments/HalberdExperimentalResearchCenter/Cards/HalberdZephyrCardController.cs
  Controller/Environments/StSimeonsCatacombs/Cards/CursedVaultCardController.cs
  Controller/Environments/StSimeonsCatacombs/Cards/TortureChamberCardController.cs
  Controller/Environments/TheWanderingIsle/Cards/AmphibiousAssaultCardController.cs
  Controller/Environments/TheWanderingIsle/Cards/TeryxCardController.cs
  Controller/Heroes/DocHavoc/Cards/ImmediateEvacCardController.cs
  Controller/Heroes/Necro/CardSubClasses/NecroCardController.cs
  Controller/Heroes/Quicksilver/Cards/FrenziedMeleeCardController.cs
  Controller/Heroes/Starlight/Cards/WarpHaloCardController.cs
  Controller/Heroes/TheStranger/Cards/GlyphOfPerceptionCardController.cs
  Controller/Villains/Anathema/Cards/TheStuffOfNightmaresCardController.cs
  Controller/Villains/Dendron/Cards/DarkDesignCardController.cs
  Controller/Villains/Dendron/Cards/LivingInkCardController.cs
  Controller/Villains/Gray/Cards/MutatedWildlifeCardController.cs
  Controller/Villains/TheRam/CharacterCards/TheRamCharacterCardController.cs
  Controller/Villains/Tiamat/CardSubClasses/TiamatCharacterCardController.cs
Labels: enhancement

#282 Gray Bug Fix
  Controller/Villains/Gray/Cards/LivingReactorCardController.cs
  Testing/Villains/GrayTests.cs
Labels: confirmed bug
