Repository SotMSteamMods/CauldronMods, pull requests merged in 2021-05, with the labels that each got.

#1304 changed ellipses character to three periods
  CauldronMods/DeckLists/Hero/LadyOfTheWoodDeckList.json
  CauldronMods/DeckLists/Hero/TitanDeckList.json
  CauldronMods/DeckLists/Villain/GrayDeckList.json
Labels: Text Issue

#1296 Terminus' Railway Spike Improvements
  CauldronMods/Controller/Heroes/Terminus/Cards/RailwaySpikeCardController.cs
Labels: enhancement

#1286 Starlight Decklist Fixes
  CauldronMods/DeckLists/Hero/StarlightDeckList.json
Labels: Text Issue

#1292 Oblask Crater's Industrious Hulk Custom UI Decision
  CauldronMods/Controller/Environments/OblaskCrater/Cards/IndustriousHulkCardController.cs
Labels: Custom UI Text

#1268 1929 Necro Incap 3 Custom UI Text
  CauldronMods/Controller/Heroes/Necro/CharacterCards/PastNecroCharacterCardController.cs
Labels: Custom UI Text

#1263 Cypher UI decision improvements
  CauldronMods/Controller/Heroes/Cypher/Cards/BackupPlanCardController.cs
  CauldronMods/Controller/Heroes/Cypher/Cards/CyborgBlasterCardController.cs
  CauldronMods/Controller/Heroes/Cypher/Cards/CyborgPunchCardController.cs
  CauldronMods/Controller/Heroes/Cypher/Cards/HeuristicAlgorithmCardController.cs
  CauldronMods/Controller/Heroes/Cypher/Cards/NeuralInterfaceCardController.cs
Labels: Custom UI Text

#1258 Text fixes
  CauldronMods/DeckLists/Villain/MenagerieDeckList.json
  CauldronMods/DeckLists/Villain/ScreaMachineDeckList.json
Labels: Text Issue

#1252 Blackwood forest not loading in oa
  CauldronMods/Controller/Environments/BlackwoodForest/Cards/VengefulSpiritsCardController.cs
  Testing/Environments/BlackwoodForestTests.cs
Labels: confirmed bug

#1306 Malichae's Zephaeren's Compass Ignores Chasm's Djinns
  CauldronMods/Controller/Heroes/Malichae/Cards/ZephaerensCompassCardController.cs
  Testing/Heroes/MalichaeTests.cs
Labels: confirmed bug

#1254 Mistress of fate subdecks
  Art/Atlas/TheMistressOfFateDayAtlas0.json
  Art/Atlas/TheMistressOfFateDayAtlas0.png
  Art/LargeCardTextures/TheMistressOfFateDay/DayOfSaints.jpg
  Art/LargeCardTextures/TheMistressOfFateDay/DayOfSinners.jpg
  Art/LargeCardTextures/TheMistressOfFateDay/DayOfSorrows.jpg
  Art/LargeCardTextures/TheMistressOfFateDay/DayOfSwords.jpg
  Art/LargeCardTextures/TheMistressOfFateDay/TheMistressOfFateDayDeckBack.jpg
  CauldronMods/DeckLists/Villain/TheMistressOfFateDeckList.json
Labels: enhancement

#1259 Drift Improvements
  Art/Atlas/DriftAtlas0.json
  CauldronMods/Controller/Heroes/Drift/CharacterCards/RedBlue/BlueAllInGoodTimeDriftCharacterCardController.cs
  CauldronMods/Controller/Heroes/Drift/CharacterCards/RedBlue/BlueDriftCharacterCardController.cs
  CauldronMods/Controller/Heroes/Drift/CharacterCards/RedBlue/BlueDriftingShadowDriftCharacterCardController.cs
  CauldronMods/Controller/Heroes/Drift/CharacterCards/RedBlue/BlueFutureDriftCharacterCardController.cs
  CauldronMods/Controller/Heroes/Drift/CharacterCards/RedBlue/BluePastDriftCharacterCardController.cs
  CauldronMods/Controller/Heroes/Drift/CharacterCards/RedBlue/BlueTestSubjectHalberdDriftCharacterCardController.cs
  CauldronMods/Controller/Heroes/Drift/CharacterCards/RedBlue/BlueThroughTheBreachDriftCharacterCardController.cs
  CauldronMods/Controller/Heroes/Drift/CharacterCards/RedBlue/RedAllInGoodTimeDriftCharacterCardController.cs
  CauldronMods/Controller/Heroes/Drift/CharacterCards/RedBlue/RedDriftCharacterCardController.cs
  CauldronMods/Controller/Heroes/Drift/CharacterCards/RedBlue/RedDriftingShadowDriftCharacterCardController.cs
  CauldronMods/Controller/Heroes/Drift/CharacterCards/RedBlue/RedFutureDriftCharacterCardController.cs
  CauldronMods/Controller/Heroes/Drift/CharacterCards/RedBlue/RedPastDriftCharacterCardController.cs
  CauldronMods/Controller/Heroes/Drift/CharacterCards/RedBlue/RedTestSubjectHalberdDriftCharacterCardController.cs
  CauldronMods/Controller/Heroes/Drift/CharacterCards/RedBlue/RedThroughTheBreachDriftCharacterCardController.cs
  CauldronMods/Controller/Heroes/Drift/CharacterCards/TestSubjectHalberdDriftCharacterCardController.cs
  Testing/Heroes/DriftVariantsTests.cs
Labels: enhancement

#1260 UI custom decision texts
  CauldronMods/Controller/Heroes/Cricket/Cards/SonicAmplifierCardController.cs
  CauldronMods/Controller/Heroes/Echelon/CardSubClasses/InOutCardController.cs
  CauldronMods/Controller/Heroes/Echelon/Cards/FindAWayInCardController.cs
  CauldronMods/Controller/Heroes/Echelon/Cards/NeedAWayOutCardController.cs
  CauldronMods/Controller/Heroes/Echelon/Cards/SurpriseAttackCardController.cs
  CauldronMods/Controller/Villains/TheMistressOfFate/Cards/ChaosButterflyCardController.cs
Labels: Custom UI Text

#1262 Damage preview improvements
  CauldronMods/Controller/Heroes/Impact/CharacterCards/ImpactCharacterCardController.cs
  CauldronMods/Controller/Heroes/Pyre/Cards/ParticleColliderCardController.cs
Labels: enhancement

#1265 Catacombs Text Cleanup
  CauldronMods/DeckLists/Environment/StSimeonsCatacombsDeckList.json
Labels: Text Issue

#1269 Oblask Crater's Invasive Growth Bug Fix
  CauldronMods/Controller/Environments/OblaskCrater/Cards/InvasiveGrowthCardController.cs
Labels: confirmed bug

#1287 The Knight assigning equipment in OA mode
  CauldronMods/Controller/Heroes/Starlight/CardSubClasses/StarlightCardController.cs
  CauldronMods/Controller/Heroes/TheKnight/CardSubClasses/RoninAssignableCardController.cs
  CauldronMods/Controller/Heroes/TheKnight/CardSubClasses/TheKnightCardController.cs
  CauldronMods/Controller/Heroes/TheKnight/Cards/CatchYourBreathCardController.cs
  CauldronMods/Controller/Heroes/TheKnight/Cards/ShortSwordCardController.cs
  CauldronMods/Controller/Heroes/TheKnight/Cards/StalwartShieldCardController.cs
  Testing/Heroes/TheKnightTests.cs
Labels: confirmed bug

#1297 Tango One's Wetwork Bug Fix in Oblivaeon
  CauldronMods/Controller/Heroes/TangoOne/Cards/WetWorkCardController.cs
  Testing/Heroes/TangoOneTests.cs
Labels: confirmed bug

#1298 FSC Continuance Wanderer's Heart of Wanderer Bug Fixes in Oblivaeon
  CauldronMods/Controller/Environments/FSCContinuanceWanderer/Cards/HeartOfTheWandererCardController.cs
  Testing/Environments/FSCContinuanceWandererTests.cs
Labels: confirmed bug

#1299 Vanish's Forewarned Bug Fixes in Oblivaeon
  CauldronMods/Controller/Heroes/Vanish/Cards/FlashReconCardController.cs
  Testing/Heroes/VanishTests.cs
Labels: confirmed bug

#1300 Terminus' Unusual suspects Bug Fix in Oblivaeon
  CauldronMods/Controller/Heroes/Terminus/Cards/UnusualSuspectsCardController.cs
  Testing/Heroes/TerminusTest.cs
Labels: confirmed bug

#1301 Tiamat's Elemental Form Improvement
  CauldronMods/Controller/Villains/Tiamat/Cards/ElementalFormCardController.cs
Labels: enhancement

#1305 Gray's Start of Turn Flipped Destruction and Fixed Point
  CauldronMods/Controller/Villains/Gray/CharacterCards/GrayCharacterCardController.cs
  Testing/CauldronBaseTest.cs
  Testing/Villains/GrayTests.cs
Labels: confirmed bug

#1307 Titan's Forbidden Archives Improvements
  CauldronMods/Controller/Heroes/Titan/Cards/ForbiddenArchivesCardController.cs
  Testing/Heroes/TitanTests.cs
Labels: enhancement

#1312 Progeny and Titan/Drift
  CauldronMods/Controller/Heroes/Drift/CardSubClasses/DriftSubCharacterCardController.cs
  CauldronMods/Controller/Heroes/Titan/SubCardClasses/TitanBaseCharacterCardController.cs
  Testing/Heroes/DriftDualVariantTests.cs
  Testing/Heroes/DriftTests.cs
  Testing/Heroes/TitanTests.cs
Labels: confirmed bug
