Repository SotMSteamMods/CauldronMods, pull requests merged in 2021-04, with the labels that each got.

#1172 Added check for user setting and logic for discarding all crash cards
  CauldronMods/Controller/Heroes/Gyrosaur/Cards/SphereOfDevastationCardController.cs
Labels: enhancement

#1171 changed GetEnumerator into foreach
  CauldronMods/Controller/Villains/Tiamat/Cards/AcidBreathCardController.cs
Labels: cleanup, good first issue

#1132 Mythos and Dangerous Investigation custom decision text
  CauldronMods/Controller/Villains/Mythos/Cards/DangerousInvestigationCardController.cs
  CauldronMods/Controller/Villains/Mythos/CharacterCards/MythosCharacterCardController.cs
Labels: Custom UI Text

#1133 Mythos challenge mode
  CauldronMods/Controller/Villains/Mythos/CardSubClasses/MythosUtilityCardController.cs
  CauldronMods/Controller/Villains/Mythos/CharacterCards/MythosCharacterCardController.cs
  CauldronMods/DeckLists/Villain/MythosDeckList.json
Labels: Challenge Mode

#1181 Villain setup Instructions Consistency
  CauldronMods/DeckLists/Villain/AnathemaDeckList.json
  CauldronMods/DeckLists/Villain/CeladrochDeckList.json
  CauldronMods/DeckLists/Villain/DendronDeckList.json
  CauldronMods/DeckLists/Villain/DynamoDeckList.json
  CauldronMods/DeckLists/Villain/GrayDeckList.json
  CauldronMods/DeckLists/Villain/MenagerieDeckList.json
  CauldronMods/DeckLists/Villain/MythosDeckList.json
  CauldronMods/DeckLists/Villain/OriphelDeckList.json
  CauldronMods/DeckLists/Villain/OutlanderDeckList.json
  CauldronMods/DeckLists/Villain/PhaseVillainDeckList.json
  CauldronMods/DeckLists/Villain/ScreaMachineDeckList.json
  CauldronMods/DeckLists/Villain/SwarmEaterDeckList.json
  CauldronMods/DeckLists/Villain/TheInfernalChoirDeckList.json
  CauldronMods/DeckLists/Villain/TheMistressOfFateDeckList.json
  CauldronMods/DeckLists/Villain/TheRamDeckList.json
  CauldronMods/DeckLists/Villain/TiamatDeckList.json
  CauldronMods/DeckLists/Villain/VectorDeckList.json
Labels: base-game-conformity

#1140 Forbidden Archives Custom Text
  CauldronMods/Controller/Heroes/Titan/Cards/ForbiddenArchivesCardController.cs
Labels: Custom UI Text

#1120 Fix for #1104: Sphere of Devastation Improvement
  CauldronMods/Controller/Heroes/Gyrosaur/Cards/SphereOfDevastationCardController.cs
  Testing/Heroes/GyrosaurTests.cs
Labels: enhancement

#1139 makeshift shelter custom text
  CauldronMods/Controller/Environments/Northspar/Cards/MakeshiftShelterCardController.cs
Labels: Custom UI Text

#1162 ScreaMachine Typo Fix
  CauldronMods/DeckLists/Villain/ScreaMachineDeckList.json
Labels: Text Issue

#1189 Swarm Eater Challenge Modes
  CauldronMods/Controller/Villains/SwarmEater/CardSubClasses/AugCardController.cs
  CauldronMods/Controller/Villains/SwarmEater/Cards/AbsorbedNanitesCardController.cs
  CauldronMods/Controller/Villains/SwarmEater/Cards/BladeAugCardController.cs
  CauldronMods/Controller/Villains/SwarmEater/Cards/FireAugCardController.cs
  CauldronMods/Controller/Villains/SwarmEater/Cards/JumperAugCardController.cs
  CauldronMods/Controller/Villains/SwarmEater/Cards/LasherAugCardController.cs
  CauldronMods/Controller/Villains/SwarmEater/Cards/SpeedAugCardController.cs
  CauldronMods/Controller/Villains/SwarmEater/Cards/StalkerAugCardController.cs
  CauldronMods/Controller/Villains/SwarmEater/Cards/SubterranAugCardController.cs
  CauldronMods/Controller/Villains/SwarmEater/Cards/VenomAugCardController.cs
  CauldronMods/Controller/Villains/SwarmEater/CharacterCards/DistributedHivemindSwarmEaterCharacterCardController.cs
  CauldronMods/Controller/Villains/SwarmEater/CharacterCards/SwarmEaterCharacterCardController.cs
  CauldronMods/DeckLists/Villain/SwarmEaterDeckList.json
  Testing/Villains/SwarmEaterTests.cs
  Testing/Villains/SwarmEaterVariantTests.cs
Labels: Challenge Mode

#1193 ram 1929 typo fix
  CauldronMods/DeckLists/Villain/TheRamDeckList.json
Labels: Text Issue

#1198 Outlander Archangel Typo
  CauldronMods/DeckLists/Villain/OutlanderDeckList.json
Labels: Text Issue

#1121 Fix for 1085 - Renegade Quicksilver Special String
  CauldronMods/Controller/Heroes/Quicksilver/CharacterCards/RenegadeQuicksilverCharacterCardController.cs
  Testing/Heroes/QuicksilverVariantsTests.cs
Labels: enhancement

#1123 Hydra tiamat Challenge + Elemental Frenzy bug fix
  CauldronMods/Controller/Villains/Tiamat/Cards/ElementalFrenzyCardController.cs
  Testing/Villains/TiamatHydraTests.cs
Labels: Challenge Mode

#1144 Impact base power improvements
  CauldronMods/Controller/Heroes/Impact/CharacterCards/ImpactCharacterCardController.cs
Labels: Custom UI Text

#1145 Bring down the house improvements
  CauldronMods/Controller/Heroes/Baccarat/Cards/BringDownTheHouseCardController.cs
  Testing/Heroes/BaccaratTests.cs
Labels: Custom UI Text

#1146 Infernal choir challenge
  CauldronMods/Controller/Villains/TheInfernalChoir/CharacterCards/TheInfernalChoirCharacterCardController.cs
  CauldronMods/DeckLists/Villain/TheInfernalChoirDeckList.json
  Testing/CauldronBaseTest.cs
  Testing/Villains/TheInfernalChoirTests.cs
Labels: Challenge Mode

#1147 Outlander challenge mode
  CauldronMods/Controller/Villains/Outlander/CharacterCards/OutlanderCharacterCardController.cs
  CauldronMods/DeckLists/Villain/OutlanderDeckList.json
  Testing/Villains/OutlanderTests.cs
Labels: Challenge Mode

#1155 Drift's Focuses Custom Text
  CauldronMods/Controller/Heroes/Drift/Cards/FutureFocusCardController.cs
  CauldronMods/Controller/Heroes/Drift/Cards/PastFocusCardController.cs
Labels: Custom UI Text

#1156 Gargoyle's Your Strength is Mine - UI Improvement
  CauldronMods/Controller/Heroes/Gargoyle/Cards/YourStrengthIsMineCardController.cs
Labels: Custom UI Text

#1158 Vector challenge redesign
  CauldronMods/Controller/Villains/Vector/CharacterCards/VectorCharacterCardController.cs
  CauldronMods/DeckLists/Villain/VectorDeckList.json
  Testing/Villains/VectorTests.cs
Labels: Challenge Mode

#1163 Mythos Missing Attribution on Rusted Artifact
  CauldronMods/DeckLists/Villain/MythosDeckList.json
Labels: Text Issue

#1164 Mistress of fate challenge mode
  CauldronMods/Controller/Villains/TheMistressOfFate/CharacterCards/TheMistressOfFateCharacterCardController.cs
  CauldronMods/DeckLists/Villain/TheMistressOfFateDeckList.json
  Testing/CauldronBaseTest.cs
  Testing/Villains/TheMistressOfFateTests.cs
Labels: Challenge Mode

#1165 Menagerie challenge mode
  CauldronMods/Controller/Villains/Menagerie/CharacterCards/MenagerieCharacterCardController.cs
  CauldronMods/DeckLists/Villain/MenagerieDeckList.json
  Testing/Villains/MenagerieTests.cs
Labels: Challenge Mode

#1166 Phase challenge mode
  CauldronMods/Controller/Villains/PhaseVillain/CharacterCards/PhaseVillainCharacterCardController.cs
  CauldronMods/DeckLists/Villain/PhaseVillainDeckList.json
  Testing/Villains/PhaseVillainTests.cs
Labels: Challenge Mode

#1174 Dual Drift - Switching Characters Custom Text
  CauldronMods/Controller/Heroes/Drift/Shift Track/DualShiftTrackUtilityCardController.cs
Labels: Custom UI Text

#1180 Phase residual desynchronization and Destroyed Obstacles
  CauldronMods/Controller/Villains/PhaseVillain/Cards/ResidualDesynchronizationCardController.cs
  Testing/Villains/PhaseVillainTests.cs
Labels: enhancement

#1182 Fix for 1170 - Post Hypnotic Gaze Associated Card Pop-up
  CauldronMods/Controller/Heroes/MagnificentMara/Cards/PostHypnoticCueCardController.cs
Labels: enhancement

#1186 Screamachine challenge mode
  CauldronMods/Controller/Villains/ScreaMachine/CardSubClasses/ScreaMachineBandCharacterCardController.cs
  CauldronMods/Controller/Villains/ScreaMachine/Cards/IrresistibleVoiceCardController.cs
  CauldronMods/Controller/Villains/ScreaMachine/CharacterCards/TheSetListCardController.cs
  CauldronMods/DeckLists/Villain/ScreaMachineDeckList.json
  Testing/Villains/ScreaMachineTests.cs
Labels: Challenge Mode

#1192 Oriphel Challenge Mode
  CauldronMods/Controller/Villains/Oriphel/CharacterCards/OriphelCharacterCardController.cs
  CauldronMods/DeckLists/Villain/OriphelDeckList.json
  Testing/Villains/OriphelTests.cs
Labels: Challenge Mode

#1195 Ram + Ram1929 challenge
  CauldronMods/Controller/Villains/TheRam/CardSubClasses/TheRamUtilityCardController.cs
  CauldronMods/Controller/Villains/TheRam/CharacterCards/PastTheRamCharacterCardController.cs
  CauldronMods/Controller/Villains/TheRam/CharacterCards/TheRamCharacterCardController.cs
  CauldronMods/DeckLists/Villain/TheRamDeckList.json
  Testing/Villains/TheRamTests.cs
  Testing/Villains/TheRamVariantTests.cs
Labels: Challenge Mode

#1209 drift typo fix
  CauldronMods/DeckLists/Hero/DriftDeckList.json
Labels: Text Issue

#1227 Typo and Icon fixes
  CauldronMods/DeckLists/Environment/FSCContinuanceWandererDeckList.json
  CauldronMods/DeckLists/Hero/PyreDeckList.json
  CauldronMods/DeckLists/Villain/TheInfernalChoirDeckList.json
  CauldronMods/DeckLists/Villain/TheRamDeckList.json
Labels: Text Issue

#1228 echelon's breakthrough custom ui text
  CauldronMods/Controller/Heroes/Echelon/Cards/BreakThroughCardController.cs
Labels: Custom UI Text

#1238 Gyro stabilizer decision improvement
  CauldronMods/Controller/Heroes/Gyrosaur/CardSubClasses/GyrosaurUtilityCardController.cs
  CauldronMods/Controller/Heroes/Gyrosaur/Cards/RecklessAlienRacingTortoiseCardController.cs
  Testing/Heroes/GyrosaurTests.cs
Labels: Custom UI Text
